# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17GAklddBMmT2US21Dedcv0sB9IqCkPp5
"""

#HLT B, 1:
import numpy as np
start = np.arange(10)
print(start)

#HLT B, 2:
import numpy as np
true = np.ones(9, dtype= bool)
newarray= true.reshape(3,3)
print(newarray)