# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vo5cf5t-i3dgZdvcFf_VyszwSQKKhfng
"""

#HLT3,3:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
array2 = np.delete(array,[1,3,5,7,9]) #Remember 0 indexing
print(array2)

#HLT3,4:
import numpy as np 
array= np.arange(1,11,1)
array[array%2==1] = -1
print(array)

#HLT3,5:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
array2= np.reshape(array,(2,5))
print(array2)

#HLT3,6:
import numpy as np
array_a = np.arange(1,6,1)
array_b = np.arange(6,11,1)
array_c = np.vstack((array_a, array_b))
print(array_c)
array_c = np.dot(array_a, array_b)
sum= np.sum(array_c)
print("total *,+ =", sum)