# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sUohjWgzLhc9gYmN7eTCZIyFqgkvvZvE
"""

#HLT3B,Extension2:
import numpy as np
array_a = ([1,2,3,4,5])
array_b = ([4,5,6,7,8,9])
array_b = np.delete(array_b,[0,1])
print(array_a,array_b)

#HLT3B,Extension3:
import numpy as np
array_a = ([1,2,3,4,5])
array_b = ([4,5,6,7,8,9])
array_c = np.append(array_a, array_b)
output_array= (array_c[3:8])
print(output_array)
solution = np.sum(output_array)
print("The sum of indexes 3 to 7 = ", solution)